### ISSUE TITLE
Data on demand 4-06:55 AM missing data status ?

### ISSUE THREAD

**Issue by noam2** [Nasdaq/NasdaqCloudDataService-SDK-Java#41]
@ruchirvaninasdaq is there any update in regards to the missing data from 4AM to 06:55AM in the Data on demand product ?

**Comment by noam2** [comment]
??

**Comment by clientsuccessnasdaq** [comment]
Hi there, 

This is Raquel from the NCDS Client Success team. 

I have been looking into this question for you. 

Can you please email clientsuccess@nasdaq.com and let us know the company name that your subscription is under? We would like to continue communicating via email. 

Thank you, 
Raquel 

NCDS Client Success
