### ISSUE TITLE
Data on demand missing data for 12-02

### ISSUE THREAD

**Issue by noam2** [Nasdaq/NasdaqCloudDataService-SDK-Java#42]
the data was not populated for 12-02. pls populate it, we need to have it

**Comment by Raquel003** [comment]
Hello, 

Thanks for your patience while our team looked into this. This has now been resolved. 

Can you please try accessing the data again for 12-02 and let us know if it works? 

We will look out for your response - please also feel free to email connect@data.nasdaq.com which is the support email we monitor regularly. 

Thank you, 
Raquel 

NCDS Client Success

**Comment by noam2** [comment]
works. what about the data from 4am -06:55am ? any news on that ?

**Comment by clientsuccessnasdaq** [comment]
Hi there,

I have been looking into this question for you.

Can you please email clientsuccess@nasdaq.com and let us know the company name that your subscription is under? We would like to continue communicating via email.

Thank you,
Raquel

NCDS Client Success
